name: Send Discord PR notification

on:
  pull_request:
    types: [opened, reopened]

jobs:
  build:
    runs-on: self-hosted
    steps:
      -
        name: Send Discord PR message
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.DISCORD_WEBHOOK_ID }}
          webhook_token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
          message: "PR opened: ${{ github.event.pull_request.title }} \n ${{ github.event.pull_request.html_url }} \n PR request by ${{ github.event.pull_request.user.login }}"