name: Send Discord PR notification

on:
  pull_request:
    types: [opened, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Send Discord PR message
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.DISCORD_WEBHOOK_ID }}
          webhook_token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
          username: "PR notification"
          message: "A new pull request opened for ${{ github.event.repository.name }} \n ${{ github.event.pull_request.html_url }} \n Please review."
